//LIST
export const LIST = {
  REQUEST: "LIST_REQUEST",
  SUCCESS: "LIST_SUCCESS",
  FAIL: "LIST_FAIL"
};

//ADD_TODO
export const ADD_TODO = {
  REQUEST: "ADD_TODO_REQUEST",
  SUCCESS: "ADD_TODO_SUCCESS",
  FAIL: "ADD_TODO_FAIL"
};

//DELETE_TODO
export const DELETE_TODO = {
  REQUEST: "DELETE_TODO_REQUEST",
  SUCCESS: "DELETE_TODO_SUCCESS",
  FAIL: "DELETE_TODO_FAIL"
};

//UPDATE_TODO
export const UPDATE_TODO = {
  REQUEST: "UPDATE_TODO_REQUEST",
  SUCCESS: "UPDATE_TODO_SUCCESS",
  FAIL: "UPDATE_TODO_FAIL"
};
